# 启动端口
server:
  port: 8080

# 数据库信息
spring:
  datasource:
    name: game # 库名
    url: jdbc:mysql://localhost:3306/game?charset=utf8 # 连接地址
    username: root # 用户名
    password: root # 密码
    driver-class-name: com.mysql.jdbc.Driver # 数据库驱动

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml


